import React,{useState,useRef} from 'react';
import {useI18n} from '../i18n.js';
import {furnitureFits,roomBounds} from '../spacePlanning.js';
export default function FurniturePlanner({layout}){
 const {t,number}=useI18n(),[roomId,setRoomId]=useState(layout.rooms[0].id),[width,setWidth]=useState(2),[depth,setDepth]=useState(.9),[position,setPosition]=useState(null),svg=useRef();
 const room=layout.rooms.find(r=>r.id===roomId),b=roomBounds(room.polygon),center=position||[(b.minX+b.maxX)/2,(b.minZ+b.maxZ)/2];
 const fits=furnitureFits(room.polygon,center,Number(width),Number(depth));
 const move=e=>{if(e.buttons!==1&&e.type!=='pointerdown')return;const point=svg.current.createSVGPoint();point.x=e.clientX;point.y=e.clientY;const p=point.matrixTransform(svg.current.getScreenCTM().inverse());setPosition([Math.max(b.minX,Math.min(b.maxX,p.x)),Math.max(b.minZ,Math.min(b.maxZ,p.y))]);};
 return <div className="buyer-stack"><p className="buyer-notice">{t('Planning sketch only. Dimensions come from our approximate model. Confirm measurements, door clearances and delivered finishes with Artwin.')}</p><div className="buyer-fields"><label>{t('Room')}<select aria-label={t('Room')} value={roomId} onChange={e=>{setRoomId(e.target.value);setPosition(null);}}>{layout.rooms.map(r=><option key={r.id} value={r.id}>{t(r.name)}</option>)}</select></label><label>{t('Furniture width (m)')}<input type="number" min="0.1" max="10" step="0.1" value={width} onChange={e=>setWidth(e.target.value)}/></label><label>{t('Furniture depth (m)')}<input type="number" min="0.1" max="10" step="0.1" value={depth} onChange={e=>setDepth(e.target.value)}/></label></div><div className="buyer-actions">{[['Sofa',2,.9],['Bed',1.8,2.1],['Table',1.4,.8]].map(([label,w,d])=><button className="buyer-secondary" key={label} onClick={()=>{setWidth(w);setDepth(d);}}>{t(label)}</button>)}<button className="buyer-secondary" onClick={()=>{setWidth(depth);setDepth(width);}}>{t('Rotate furniture')}</button></div><svg ref={svg} className="furniture-sketch" viewBox={`${b.minX-.4} ${b.minZ-.4} ${b.width+.8} ${b.depth+.8}`} role="img" aria-label={t('Approximate room and furniture footprint')} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);move(e);}} onPointerMove={move}><polygon points={room.polygon.map(p=>p.join(',')).join(' ')} fill="#f4f0e4" stroke="#596452" strokeWidth=".06"/>{Number(width)>0&&Number(depth)>0&&<rect x={center[0]-width/2} y={center[1]-depth/2} width={width} height={depth} rx=".08" fill={fits?'#929f7c':'#dbab87'} stroke={fits?'#405334':'#9d503b'} strokeWidth=".04"/>}</svg><p role="status">{t(fits?'The footprint is inside the approximate room boundary.':'The footprint crosses the room boundary or has invalid dimensions.')}</p><p className="buyer-muted">{t('Drag the furniture, or use the position sliders. Door swings and other furniture are not checked.')}</p><div className="buyer-fields"><label>{t('Horizontal position')}<input type="range" min={b.minX} max={b.maxX} step="0.05" value={center[0]} onChange={e=>setPosition([Number(e.target.value),center[1]])}/></label><label>{t('Vertical position')}<input type="range" min={b.minZ} max={b.maxZ} step="0.05" value={center[1]} onChange={e=>setPosition([center[0],Number(e.target.value)])}/></label></div><p>{t('Approximate room extent')}: {number(b.width,2)} × {number(b.depth,2)} {t('m')}</p></div>;
}
