import React,{useState} from 'react';
import {projects,projectSource,projectHref,projectImage,apartmentHref} from '../projects.js';
import FloorPlan from './FloorPlan.jsx';
import Icon from './Icon.jsx';
import {getLayout} from '../layouts/index.js';

export function CollectionHeader(){return <header className="collection-header"><a href="#/projects" aria-label="Artwin home"><img src={`${import.meta.env.BASE_URL}artwin-logo.png`} width="287" height="88" alt="ARTWIN"/></a><span className="collection-header-caption">A NEW PERSPECTIVE ON HOME</span><a className="collection-nav" href="#/projects" onClick={e=>{const heading=document.getElementById('project-list-title');if(heading){e.preventDefault();heading.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});heading.focus({preventScroll:true});}}}>Our projects <Icon name="arrow" size={17}/></a></header>;}
export function CollectionFooter(){return <footer className="collection-footer"><span>ARTWIN <span className="footer-divider">/</span> Spaces for living</span><p>Project imagery & information from <a href={projectSource} target="_blank" rel="noreferrer">Artwin’s official collection ↗</a></p><span>Interactive apartment previews</span></footer>;}
function ProjectImage({project,eager=false,className=''}){
  const [failed,setFailed]=useState(false);
  return <div className={`project-image ${className}`}>
    {failed?<div className="project-image-fallback"><span>{project.name}</span><small>Project image unavailable</small></div>:<img src={projectImage(project)} alt={`${project.name} — Artwin project view`} loading={eager?'eager':'lazy'} decoding="async" onError={()=>setFailed(true)}/>}
  </div>;
}
function Availability({project}){return <span className={`project-availability ${project.plans.length?'available':''}`}><span/>{project.plans.length?`${project.plans.length} interactive apartment${project.plans.length===1?'':'s'}`:'Floor plans coming soon'}</span>;}
export default function ProjectCollection(){
  const [city,setCity]=useState('All'),[query,setQuery]=useState('');
  const featured=projects.find(p=>p.id==='tokyo-city');
  const filtered=projects.filter(p=>(city==='All'||p.city===city)&&`${p.name} ${p.nativeName||''} ${p.city} ${p.address}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <main className="collection-main">
    <section className="collection-intro"><div><span className="collection-kicker">THE ARTWIN COLLECTION</span><h1 data-page-title tabIndex={-1}>Find your place.<br/><em>Imagine your life.</em></h1></div><div className="collection-intro-copy"><p>Every home begins with a place.<br/>Choose a project. Explore the possibilities.</p><div><span>{projects.length} projects</span><i/><span>2 cities</span><i/><span>One new perspective</span></div></div></section>
    <section className="collection-featured" aria-labelledby="featured-title"><ProjectImage project={featured} eager/><div className="featured-copy"><span className="collection-kicker">YOUR FIRST LOOK INSIDE</span><h2 id="featured-title">Tokyo City</h2><p>A place to slow down.<br/>A home to make your own.</p><span className="featured-location">{featured.city} · {featured.address}</span><a className="collection-button" href={projectHref(featured)}>Explore Tokyo City <Icon name="arrow"/></a><span className="featured-note">Six floor plans · 52.10–134.68 m² · Explore in 3D</span></div></section>
    <section className="project-browser" aria-labelledby="project-list-title"><div className="project-browser-heading"><div><span className="collection-kicker">DISCOVER THE COLLECTION</span><h2 id="project-list-title" tabIndex={-1}>Choose your project</h2></div><p>One collection. Different ways to live.</p></div>
      <div className="project-filters"><div className="city-filters" role="group" aria-label="Filter projects by city">{['All','Bishkek','Osh'].map(c=><button key={c} aria-pressed={city===c} onClick={()=>setCity(c)}>{c==='All'?'All projects':c}<span>{c==='All'?projects.length:projects.filter(p=>p.city===c).length}</span></button>)}</div><label className="project-search"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input type="search" aria-label="Search projects" placeholder="Find a project" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
      <p className="project-result-count" role="status">{filtered.length} {filtered.length===1?'project':'projects'}{city!=='All'?` in ${city}`:''}</p>
      <div className="project-grid">{filtered.map(p=><a key={p.id} className="project-card" href={projectHref(p)} aria-label={`Explore ${p.name}`}><div className="project-card-visual"><ProjectImage project={p}/><span className="project-city">{p.city}</span><span className="project-card-arrow"><Icon name="arrow"/></span></div><div className="project-card-copy"><div className="project-card-heading"><h3>{p.name}</h3><span>{p.type}</span></div><p>{p.address}</p><Availability project={p}/></div></a>)}</div>
      {!filtered.length&&<div className="project-empty-search"><h3>No projects found.</h3><p>Try a different name or city.</p><button onClick={()=>{setCity('All');setQuery('');}}>Clear filters <Icon name="reset" size={16}/></button></div>}
    </section>
  </main>;
}
export function ProjectPage({project}){const [bedrooms,setBedrooms]=useState('All');const visiblePlans=project.plans.filter(p=>bedrooms==='All'||p.bedrooms===bedrooms);return <main className="project-detail">
  <nav className="collection-breadcrumb" aria-label="Breadcrumb"><a href="#/projects">All projects</a><Icon name="chevron" size={13}/><span aria-current="page">{project.name}</span></nav>
  <section className="project-overview"><div className="project-overview-copy"><span className="collection-kicker">{project.city} <span>/</span> {project.type}</span><h1 data-page-title tabIndex={-1}>{project.name}</h1>{project.nativeName&&<span className="project-native-name">{project.nativeName}</span>}<p>{project.description}</p><div className="project-address">{project.address}</div><Availability project={project}/><a className="project-source" href={project.sourceUrl} target="_blank" rel="noreferrer">About the project on Artwin ↗</a></div><ProjectImage project={project} eager/></section>
  <section className="project-plans" aria-labelledby="floor-plans-title"><div className="project-browser-heading"><div><span className="collection-kicker">PICTURE YOUR EVERYDAY</span><h2 id="floor-plans-title">{project.type==='Business centre'?'Explore the spaces':'Find your floor plan'}</h2></div><p>{project.plans.length?'Six residences. Find the space that feels like you.':'More ways to explore are on the way.'}</p></div>
    {project.plans.length?<><div className="plan-filters" role="group" aria-label="Filter apartments by bedrooms">{['All',1,2,3].map(n=><button key={n} aria-pressed={bedrooms===n} onClick={()=>setBedrooms(n)}>{n==='All'?'All floor plans':`${n} bedroom${n===1?'':'s'}`}</button>)}<span role="status">{visiblePlans.length} floor plans</span></div><div className="apartment-grid">{visiblePlans.map(plan=><article key={plan.id} className="apartment-card"><div className="apartment-plan-preview"><span>THE FLOOR PLAN</span><FloorPlan layout={getLayout(plan.id)} interactive={false}/></div><div className="apartment-card-copy"><span className="collection-kicker">INTERACTIVE APARTMENT · {String(project.plans.indexOf(plan)+1).padStart(2,'0')}</span><h3>{plan.name}</h3><div className="apartment-metrics"><div><strong>{plan.area.toFixed(2)}<small> m²</small></strong><span>Advertised area</span></div><div><strong>{plan.bedrooms}</strong><span>{plan.bedrooms===1?'Bedroom':'Bedrooms'}</span></div><div><strong>{plan.bathrooms}</strong><span>{plan.bathrooms===1?'Bathroom':'Bathrooms'}</span></div></div><p>{plan.description}</p><a className="collection-button" href={apartmentHref(project,plan)} aria-label={`Explore ${plan.area.toFixed(2)} m² in 3D`}>Explore in 3D <Icon name="arrow"/></a><span className="apartment-preview-note">Dollhouse · Guided tour · Walkthrough</span><small className="apartment-accuracy">Approximate furnished visualization based on the supplied floor plan.</small></div></article>)}</div></>:<div className="project-coming-soon"><div className="coming-soon-mark"><Icon name="plan" size={34}/></div><div><span className="collection-kicker">COMING TO THE COLLECTION</span><h3>{project.type==='Business centre'?'Space previews are on the way.':'Floor plans are on the way.'}</h3><p>{project.name}’s interactive spaces aren’t available yet.<br/>For now, step inside our first residence at Tokyo City.</p><a href={projectHref(projects.find(p=>p.id==='tokyo-city'))}>Explore Tokyo City <Icon name="arrow" size={18}/></a></div></div>}
  </section>
</main>;}
