async(page)=>{
 const errors=[],warnings=[],failed=[];const timings=[];const error=e=>errors.push(String(e)),log=m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning')warnings.push(m.text());},fail=r=>failed.push(r.url());
 page.on('pageerror',error);page.on('console',log);page.on('requestfailed',fail);
 try{
 await page.setViewportSize({width:1440,height:960});await page.goto('http://127.0.0.1:4173/Artwin/#/projects/tokyo-city/apartments/four-room-134');await page.reload();await page.waitForFunction(()=>!document.querySelector('.enter-button')?.disabled);
 await page.getByRole('button',{name:'Step inside',exact:true}).click();await page.locator('.transition-fade.active').waitFor({state:'hidden'});
 for(const id of ['hall','bath2','hall','bath3','hall','bath2','hall','bath3']){await page.evaluate(()=>{cancelAnimationFrame(window.__mirrorRAF);window.__gaps=[];window.__last=performance.now();window.__measure=true;const tick=t=>{if(!window.__measure)return;window.__gaps.push(t-window.__last);window.__last=t;window.__mirrorRAF=requestAnimationFrame(tick)};window.__mirrorRAF=requestAnimationFrame(tick)});const start=Date.now();await page.getByRole('combobox',{name:'Select a room'}).selectOption(id);await page.locator('.transition-fade.active').waitFor({state:'hidden'});await page.waitForTimeout(700);timings.push({id,elapsed:Date.now()-start,...await page.evaluate(()=>{window.__measure=false;cancelAnimationFrame(window.__mirrorRAF);const a=window.__gaps.sort((a,b)=>a-b);return {maxGap:Math.round(a.at(-1)||0),p95:Math.round(a[Math.floor(a.length*.95)]||0)}})});}
 const t=await page.locator('.plan-player').getAttribute('transform'),v=t.match(/-?\d+(?:\.\d+)?/g).map(Number),dx=1.5-v[0],dz=9-v[1];let delta=Math.atan2(-dx,-dz)+v[2]*Math.PI/180;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;const pitch=Math.atan2(1.3-1.645,Math.hypot(dx,dz)),b=await page.locator('canvas').boundingBox();
 const n=Math.ceil(Math.max(Math.abs(delta/.003),Math.abs(pitch/.003))/200);for(let i=0;i<n;i++){const x=b.x+b.width*.5,y=b.y+b.height*.4;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x-delta/.003/n,y-pitch/.003/n,{steps:6});await page.mouse.up();}
 await page.waitForTimeout(500);await page.screenshot({path:'output/playwright/bathroom-shower.png'});
 await page.getByRole('combobox',{name:'Graphics quality'}).selectOption('low');await page.setViewportSize({width:390,height:844});await page.getByRole('combobox',{name:'Select a room'}).selectOption('bath2');await page.locator('.transition-fade.active').waitFor({state:'hidden'});await page.waitForTimeout(500);await page.screenshot({path:'output/playwright/bathroom-mobile.png'});
 if(timings.some(t=>t.maxGap>2000))throw Error('Mirror entry exceeded 2s: '+JSON.stringify(timings));if(errors.length||failed.length)throw Error(JSON.stringify({errors,failed}));return{result:'PASS',timings,errors,failed,warnings:[...new Set(warnings)],checks:['live mirror','bathroom room changes','shower','mobile Light quality']};
 }finally{await page.evaluate(()=>{window.__measure=false;cancelAnimationFrame(window.__mirrorRAF);});page.off('pageerror',error);page.off('console',log);page.off('requestfailed',fail);}
}
