// Generated from the source registry by scripts/compile-catalog.mjs.
export const catalogPlans=[
  {
    "id": "hayat-52",
    "project": "hayat",
    "area": 52.34,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "hayat-0.jpg",
    "evidence": "drawing"
  },
  {
    "id": "hayat-55",
    "project": "hayat",
    "area": 55.57,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "hayat-1.jpg",
    "evidence": "drawing"
  },
  {
    "id": "hayat-89",
    "project": "hayat",
    "area": 89.56,
    "bedrooms": 2,
    "bathrooms": 2,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "hayat-2.jpg",
    "evidence": "drawing"
  },
  {
    "id": "hayat-96",
    "project": "hayat",
    "area": 96.44,
    "bedrooms": 2,
    "bathrooms": 2,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "hayat-3.jpg",
    "evidence": "drawing"
  },
  {
    "id": "hayat-154",
    "project": "hayat",
    "area": 154.09,
    "bedrooms": 3,
    "bathrooms": 3,
    "name": "Four-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "hayat-4.jpg",
    "evidence": "drawing"
  },
  {
    "id": "urpaq-park-54-a",
    "project": "urpaq-park",
    "area": 54.21,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "urpaq-park-0.jpg",
    "evidence": "drawing"
  },
  {
    "id": "urpaq-park-54-b",
    "project": "urpaq-park",
    "area": 54.21,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "urpaq-park-0.jpg",
    "evidence": "drawing"
  },
  {
    "id": "urpaq-park-78-a",
    "project": "urpaq-park",
    "area": 78.88,
    "bedrooms": 1,
    "bathrooms": 2,
    "name": "Two-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "urpaq-park-1.jpg",
    "evidence": "drawing"
  },
  {
    "id": "urpaq-park-78-b",
    "project": "urpaq-park",
    "area": 78.88,
    "bedrooms": 1,
    "bathrooms": 2,
    "name": "Two-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "urpaq-park-1.jpg",
    "evidence": "drawing"
  },
  {
    "id": "urpaq-park-84",
    "project": "urpaq-park",
    "area": 84.84,
    "bedrooms": 1,
    "bathrooms": 2,
    "name": "Two-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "urpaq-park-2.jpg",
    "evidence": "drawing"
  },
  {
    "id": "urpaq-park-114",
    "project": "urpaq-park",
    "area": 114.73,
    "bedrooms": 2,
    "bathrooms": 2,
    "name": "Three-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "urpaq-park-3.jpg",
    "evidence": "drawing"
  },
  {
    "id": "urpaq-park-122",
    "project": "urpaq-park",
    "area": 122.62,
    "bedrooms": 2,
    "bathrooms": 2,
    "name": "Three-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "urpaq-park-4.jpg",
    "evidence": "drawing"
  },
  {
    "id": "urpaq-park-152",
    "project": "urpaq-park",
    "area": 152.64,
    "bedrooms": 3,
    "bathrooms": 3,
    "name": "Four-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "urpaq-park-5.jpg",
    "evidence": "drawing"
  },
  {
    "id": "urpaq-park-154",
    "project": "urpaq-park",
    "area": 154.73,
    "bedrooms": 3,
    "bathrooms": 3,
    "name": "Four-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "urpaq-park-6.jpg",
    "evidence": "drawing"
  },
  {
    "id": "esentai-36",
    "project": "esentai",
    "area": 36.71,
    "bedrooms": 0,
    "bathrooms": 1,
    "name": "One-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "esentai-0.jpg",
    "evidence": "drawing"
  },
  {
    "id": "esentai-37",
    "project": "esentai",
    "area": 37.02,
    "bedrooms": 0,
    "bathrooms": 1,
    "name": "One-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "esentai-0.jpg",
    "evidence": "drawing"
  },
  {
    "id": "esentai-40",
    "project": "esentai",
    "area": 40.7,
    "bedrooms": 0,
    "bathrooms": 1,
    "name": "One-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "esentai-1.jpg",
    "evidence": "drawing"
  },
  {
    "id": "esentai-41",
    "project": "esentai",
    "area": 41.33,
    "bedrooms": 0,
    "bathrooms": 1,
    "name": "One-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "esentai-1.jpg",
    "evidence": "drawing"
  },
  {
    "id": "esentai-51",
    "project": "esentai",
    "area": 51.41,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "esentai-2.jpg",
    "evidence": "drawing"
  },
  {
    "id": "esentai-56",
    "project": "esentai",
    "area": 56.04,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Two-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "esentai-2.jpg",
    "evidence": "drawing"
  },
  {
    "id": "esentai-44",
    "project": "esentai",
    "area": 44.67,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "esentai-3.jpg",
    "evidence": "drawing"
  },
  {
    "id": "esentai-45",
    "project": "esentai",
    "area": 45.74,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "esentai-3.jpg",
    "evidence": "drawing"
  },
  {
    "id": "esentai-65",
    "project": "esentai",
    "area": 65.66,
    "bedrooms": 2,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "esentai-4.jpg",
    "evidence": "drawing"
  },
  {
    "id": "esentai-66",
    "project": "esentai",
    "area": 66.01,
    "bedrooms": 2,
    "bathrooms": 2,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "esentai-5.jpg",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-41-59",
    "project": "boston-tower",
    "area": 41.59,
    "bedrooms": 0,
    "bathrooms": 1,
    "name": "One-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "boston-tower-1.png",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-41-34",
    "project": "boston-tower",
    "area": 41.34,
    "bedrooms": 0,
    "bathrooms": 1,
    "name": "One-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "boston-tower-2.png",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-44",
    "project": "boston-tower",
    "area": 44.58,
    "bedrooms": 0,
    "bathrooms": 1,
    "name": "One-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "boston-tower-3.png",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-46",
    "project": "boston-tower",
    "area": 46.91,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "boston-tower-4.png",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-53",
    "project": "boston-tower",
    "area": 53.95,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "boston-tower-5.png",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-66",
    "project": "boston-tower",
    "area": 66.78,
    "bedrooms": 1,
    "bathrooms": 2,
    "name": "Two-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "boston-tower-6.png",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-67",
    "project": "boston-tower",
    "area": 67.81,
    "bedrooms": 1,
    "bathrooms": 2,
    "name": "Two-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "boston-tower-7.png",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-71",
    "project": "boston-tower",
    "area": 71.93,
    "bedrooms": 1,
    "bathrooms": 2,
    "name": "Two-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "boston-tower-8.png",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-73",
    "project": "boston-tower",
    "area": 73.46,
    "bedrooms": 1,
    "bathrooms": 2,
    "name": "Two-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "boston-tower-9.png",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-100",
    "project": "boston-tower",
    "area": 100.7,
    "bedrooms": 2,
    "bathrooms": 3,
    "name": "Three-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "boston-tower-10.png",
    "evidence": "drawing"
  },
  {
    "id": "boston-tower-106",
    "project": "boston-tower",
    "area": 106.56,
    "bedrooms": 2,
    "bathrooms": 3,
    "name": "Three-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "boston-tower-0.png",
    "evidence": "drawing"
  },
  {
    "id": "tokyo-47",
    "project": "tokyo",
    "area": 47.08,
    "bedrooms": 0,
    "bathrooms": 1,
    "name": "One-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "tokyo-0.png",
    "evidence": "render"
  },
  {
    "id": "tokyo-52",
    "project": "tokyo",
    "area": 52.24,
    "bedrooms": 1,
    "bathrooms": 1,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "tokyo-2.png",
    "evidence": "render"
  },
  {
    "id": "tokyo-75",
    "project": "tokyo",
    "area": 75.49,
    "bedrooms": 2,
    "bathrooms": 2,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "tokyo-4.png",
    "evidence": "render"
  },
  {
    "id": "tokyo-89",
    "project": "tokyo",
    "area": 89.38,
    "bedrooms": 2,
    "bathrooms": 2,
    "name": "Three-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "tokyo-6.png",
    "evidence": "render"
  },
  {
    "id": "tokyo-100",
    "project": "tokyo",
    "area": 100.59,
    "bedrooms": 2,
    "bathrooms": 2,
    "name": "Three-room residence",
    "description": "Distinct living and private spaces, arranged around a welcoming entrance hall.",
    "viewer": "furnished-layout",
    "openLiving": false,
    "reference": "tokyo-8.png",
    "evidence": "render"
  },
  {
    "id": "tokyo-110",
    "project": "tokyo",
    "area": 110.12,
    "bedrooms": 3,
    "bathrooms": 2,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "tokyo-10.png",
    "evidence": "render"
  },
  {
    "id": "tokyo-158",
    "project": "tokyo",
    "area": 158.06,
    "bedrooms": 4,
    "bathrooms": 3,
    "name": "Euro residence",
    "description": "An open living space with private rooms and practical everyday storage.",
    "viewer": "furnished-layout",
    "openLiving": true,
    "reference": "tokyo-12.png",
    "evidence": "render"
  }
];
